name: "Tests: E2E"
on: [pull_request]
  workflow_dispatch:
    inputs:
      project:
        description: 'Tested project'
        required: true
        default: 'blog'
      environment:
        description: 'Tested environment'
        required: true
        default: 'live'

env:
  PROJECT: ${{ github.event.inputs.project }}
  TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: add environment variables
        run: npm ci
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: run tests
        run: npm run test